services:
  db:
    image: mariadb:10.11
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: aluno123

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 20.110.65.35:3306
    environment:
      - PMA_ARBITRARY=1
  web:
    image: nginx
    ports:
      - "8090:80"
    volumes:
      - ./meufrontend:/usr/share/nginx/html

#docker ps

#docker compose up -d
